services:
  - type: web
    name: guvi-internship
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASS
        sync: false
      - key: MYSQL_DB
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        sync: false
      - key: MONGO_COL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASS
        sync: false
